# Generated by Django 4.2.6 on 2024-02-25 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UoMApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='studentID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='StudyUnit',
            fields=[
                ('unitName', models.CharField(max_length=50)),
                ('unitID', models.AutoField(primary_key=True, serialize=False)),
                ('studyUnits', models.ManyToManyField(to='UoMApp.course')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='courseID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UoMApp.course'),
        ),
    ]
