# Generated by Django 4.2.6 on 2024-02-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UoMApp', '0002_course_alter_student_studentid_studyunit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyunit',
            name='studyUnits',
        ),
        migrations.AddField(
            model_name='course',
            name='studyUnits',
            field=models.ManyToManyField(to='UoMApp.studyunit'),
        ),
    ]
