# Generated by Django 4.2.6 on 2024-02-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UoMApp', '0003_remove_studyunit_studyunits_course_studyunits'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyunit',
            name='unitCode',
            field=models.CharField(default='SDC105', max_length=20, unique=True),
        ),
    ]
