# Generated by Django 4.2.6 on 2024-02-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UoMApp', '0004_studyunit_unitcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyunit',
            name='unitCode',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
