# Generated by Django 4.2.6 on 2024-02-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UoMApp', '0006_alter_studyunit_unitcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='studyUnits',
            field=models.ManyToManyField(blank=True, to='UoMApp.studyunit'),
        ),
    ]
