# Generated by Django 4.2.6 on 2024-02-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UoMApp', '0007_alter_course_studyunits'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseCode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
